language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - python bootstrap.py
  - bin/buildout -c postgres.cfg
before_script:
  - sudo -u postgres createuser $USER
  - sudo -u postgres createdb --owner=$USER zope_sqlalchemy_tests
script:
  - bin/test
  - bin/testpg
