language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
before_install:
  - DATA_DIR=$(sudo -u postgres psql postgres -c "SHOW data_directory;" -q -t | head -1)
  - 'echo "max_prepared_transactions = 10" | sudo tee -a "${DATA_DIR:1}/postgresql.conf"'
  - sudo service postgresql restart
  - sudo -u postgres createdb --owner=$USER zope_sqlalchemy_tests
  - pip install -U setuptools
install:
  - python bootstrap.py
  - bin/buildout -c postgres.cfg
script:
  - bin/test
  - bin/testpg
  - bin/testpg2
